version: 0.2

phases:

  install:
    runtime-versions:
      dotnet: 8.0

  build:
    commands:

      - echo "Repository structure"

      - ls -R

      - cd app

      - dotnet restore

      - dotnet publish -c Release -o output

  post_build:
    commands:

      - cp ../appspec.yml output/

      - cp -r scripts output/

artifacts:

  files:
    - '**/*'

  base-directory: app/output
